<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Entities\AreaOfLife;
use App\Entities\Symptom;

class SymptomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // ['Ich würde mir gern finanziell mehr leisten können', 'Dein Einkommen scheint nicht auszureichen um dir deine Lebensträume zu erfüllen. Einerseits gibt es klare Regeln und Strategien, wie man seiner finanziellen Situation einen Boost geben kann - z.B. finanzielle Freiheit durch Unternehmertum oder passive Einkommensströme durch sinnvolles Investieren. Andererseits lohnt es sich auch, deine Erwartungen an das Leben zu überprüfen und zu entscheiden, ob es wirklich materielle Dinge sind, die dich glücklich machen.', '7	3	1	0	0	Ich muss finanziell erfolgreich sein	https://www.amazon.de/Money-einfachen-Schritte-finanziellen-Freiheit/dp/389879914X/ref=sr_1_5?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=finanzielle+freiheit&qid=1582546718&s=books&sr=1-5	https://images-na.ssl-images-amazon.com/images/I/51VsTzyPjKL._SX338_BO1,204,203,200_.jpg	Basierend auf umfangreichen Recherchen und Interviews mit mehr als 50 Starinvestoren, wie Warren Buffett oder Star-Hedgefondsmanager Carl Icahn, hat Robbins die besten Strategien für die private finanzielle Absicherung entwickelt. Sein Werk bündelt die Expertise erfolgreicher Finanzmarktakteure und seine Beratungserfahrung. Selbst komplexe Anlagestrategien werden verständlich erläutert, ohne an Präzision einzubüßen. In 7 Schritten zur finanziellen Unabhängigkeit - praxisnah und für jeden umsetzbar.
        // ['Ich werde für meine Leistung nicht ausreichend bezahlt', 'Wenn du das Gefühl hast, für deinen Job nicht ausreichend bezahlt zu werden, kannst du zunächst die Frage klären, ob es objektive Möglichkeiten gibt, um deine Leistung monetär zu bewerten. Wenn das nicht der Fall ist und nur du persönlich der Meinung bist, du verdienst eine höhere Vergütung, dann gibt es mehrere Optionen: Du könntest z.B. deinen Chef um ein Gespräch bitten und ihm erklären, was du für die Firma leistest. Achte unbedingt darauf, dass du dich gut vorbereitest, indem du alle Punkte auflistest und diese im besten Fall anhand von Zahlen belegen kannst. Oder du beweist dein Engagement, indem du proaktiv mehr Verantwortung übernimmst. Du hast außerdem immer die Möglichkeit, deinen Job zu wechseln - gerade bei einem Jobwechsel werden oft Gehaltssprünge von über 20% Plus erreicht. Das Wichtigste ist, dass du selbst den Wert deiner Arbeit kennst und diesen selbstbewusst vetrittst.', '5	2	3	0	0	Wenn ich mehr verdiene bin ich mehr wert	https://www.amazon.de/Geheime-Tricks-mehr-Gehalt-SPIEGEL-Bestsellers/dp/3442174287/ref=sr_1_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=mehr+gehalt&qid=1582547138&s=books&sr=1-1	https://images-na.ssl-images-amazon.com/images/I/51ISkwBH99L._SX339_BO1,204,203,200_.jpg	Mehr als zwei Drittel aller Deutschen sind unzufrieden mit ihrem Einkommen. Bei einer Gehaltsverhandlung treten sie ihrem Chef oft unsicher und nervös gegenüber. Martin Wehrle, selbst Chef und erfahrener Gehaltscoach, weiß: Es ist gar nicht so schwer, eine Gehaltserhöhung durchzusetzen – solange man selbstbewusst auftritt und das Gespräch gründlich vorbereitet. In neun unterhaltsamen Kapiteln führt er Schritt für Schritt zur erhofften Lohnerhöhung. Mit diesen Tricks kann jeder Chef überzeugt werden!
        // ['Ich weiß nicht welcher Beruf mich glücklich machen würde', 'Falls du deine beruflichen Ziele nicht kennst, wird es höchste Zeit, dass du in diesem Punkt Klarheit gewinnst. Wir verbingen, abgesehen vom Schlafen, die meiste Zeit mit unserer Arbeit. In diesem Punkt herrscht in der Psychologie Einigkeit: Ein nicht erfüllender Job führt zu Stress und langfristig zu Krankheiten wie Burn-out und Depressionen. Es gibt Methoden, mit denen du Schritt-für-Schritt herausfindest, welcher Beruf zu dir passt und dich nachhaltig glücklich macht.', '10	3	2	1	0	Ich werde beruflich nie erfolg haben	https://www.amazon.de/Karriere-Navigator-B%C3%BCcher-Angelika-Gulder/s?k=Karriere-Navigator&rh=n%3A186606%2Cp_lbr_books_authors_browse-bin%3AAngelika+Gulder	https://images-na.ssl-images-amazon.com/images/I/51esQdBu-AL._SX324_BO1,204,203,200_.jpg	Seit mehr als zehn Jahren unterstützt "Finde den Job, der dich glücklich macht" tausende Menschen auf der Suche nach ihrer Berufung und einem erfüllten Berufsleben. Der Karriere-Navigator ist die Orientierungshilfe auf dem Weg zu mehr Glück und Zufriedenheit im(Berufs-)Leben. Das bestätigt auch die Stiftung Warentest. Sie hat das Buch zum Testsieger unter einem Dutzend Karriere-Ratgebern erkoren. Egal wie alt, in welcher Lebensphase oder wo Sie sind: Der Beruf Ihrer Träume ist zum Greifen nah! "Wie man sich seiner Talente und Ziele bewusst wird, zeigt Angelika Gulder in ihrem renommierten Klassiker zur Berufswahl." Karriereführer
        // ['Ich würde mich gern zur Führungskraft entwickeln', 'Du gibst an, dass du gern mehr Verantwortung tragen möchtest. Zunächst ist es wichtig, dass du für dich definierst, was genau mehr Verantwortung bedeutet - möchtest du ein größeres Aufgabenfeld oder vielleicht Personalverantwortung. Sobald du das für dich herausgefunden hast, kannst du in den Lösungsmodus übergehen. Wenn du dich z.B. zur Führungskraft weiterentwickeln möchtest, sprich mit deinem Vorgesetzten darüber und frage ihn, ob er dich dabei unterstützen kann. Alternativ kannst du dich auch privat weiterbilden und dir neue Kompetenzen aneignen, die dich für verantwortungsvollere Aufgaben qualifizieren.', '3	2	1	0	0	Ich muss mich beweisen	https://www.amazon.de/F%C3%BChrung-Leadership-Praxis-erfolgreichen-Mitarbeitergespr%C3%A4che/dp/3965832638/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=f%C3%BChrung&qid=1582547780&s=books&sr=1-3	https://images-na.ssl-images-amazon.com/images/I/410qAnz9VrL._SX327_BO1,204,203,200_.jpg	Will ein Unternehmen erfolgreich auf dem Markt agieren, kommt es vor allem auf die richtige Mitarbeiterführung an! Denn nur wenn eine Führungskraft die richtige Arbeitsatmosphäre schafft und die Mitarbeiter auch entsprechend motiviert, erbringen diese auch Bestleistungen. Jedoch herrscht heutzutage in vielen Abteilungen und Teams keine besonders gute Stimmung. Das führt zu Unzufriedenheit, mangelnder Motivation und auch zu einem höheren Krankheitsgrad. Der Grund ist nur allzu oft ein falscher Führungsstil des Team- oder Abteilungsleiters. Wie sich das ändern lässt, verrät Reinhard Thieler-Unge in diesem einzigartigen Buch.
        // ['Ich kenne meine Berufung lebe sie aber noch nicht', 'Wenn du deine Berufung schon gefunden hast, gehörst du zu einer ganz kleinen Zahl von Menschen, die zu dieser Erkenntnis kommen. Das ist schon mehr als die halbe Miete :) Die große Frage ist jetzt: Warum steckst du noch in deinem "alten" Leben fest und folgst deiner Bestimmung noch nicht? Traust du dich nicht? Hast du Angst was dein Umfeld davon halten könnte? Fehlen dir bestimmte Fähigkeiten? Egal welche Gründe du findest, um nicht loszugehen, mache dir bewusst, dass deine innere Stimme immer lauter wird - bis du auf sie hörst. Lerne dich und deine Ängste besser kennen und befreie dich von ihnen. Eigne dir fehlende Kompetenzen an, die du für deinen Traumjob benötigst. Gehe die notwendigen Schritte und vertraue darauf, dass es sich lohnt. Denn das tut es!', '6	3	1	0	0	Ich schaffe das nicht	https://www.amazon.de/Pers%C3%B6nlichkeitsentwicklung-360%C2%B0-System-SELBSTDISZIPLIN-SELBSTBEWUSSTSEIN/dp/3965833111/ref=sr_1_2_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=erfolg&qid=1582548397&s=books&sr=1-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFQUTgzN0lOWlJQVlUmZW5jcnlwdGVkSWQ9QTA3NzcxNTgxMkZIMVhORkxMUzFUJmVuY3J5cHRlZEFkSWQ9QTAxNjM3NDAzSVhMODBDV1RBTUJEJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==	https://images-na.ssl-images-amazon.com/images/I/51OwJI2K6gL._SX350_BO1,204,203,200_.jpg	Haben Sie auch häufig das Gefühl, nicht Ihr volles Potenzial auszuschöpfen? Streben Sie auch nach mehr im Leben? Wollen Sie die beste Version ihrer selbst werden? Wenn Sie eine oder mehrere dieser Fragen mit ja beantworten können, dann sollten Sie unbedingt dieses Buch lesen! Viele Menschen beschäftigen sich zwar regelmäßig mit dem Thema Persönlichkeitsentwicklung, aber nur die Wenigsten erreichen dauerhafte Erfolge. Das Problem: Es fehlt häufig an System, Struktur und Praxisnähe. Denn ohne diese können keine neuen Gewohnheiten aufgebaut werden und somit keine langfristigen Erfolge garantiert werden. Genau hier unterscheidet sich dieses Buch von vielen anderen Büchern!
        // ['Ich sehe keine Aufstiegsmöglichkeiten', 'Manchmal merken wir, dass wir in unserem Job an eine Decke stoßen und entweder nicht mehr sonderlich viel dazulernen können oder unser Arbeitgeber ist so strukturiert, dass Aufstiegsmöglichkeiten kaum realistisch sind. Wenn wir das feststellen, macht es vermutlich Sinn, sich nach einem neuen Job umzuschauen. Sei dabei aber ehrlich zu dir. Wenn für dich Aufstiegsmöglichkeiten z.B. nur eine Gehaltserhöhung bedeuten, ist Vorsicht geboten - Studien haben belegt, dass mehr Geld auf dem Gehaltszettel uns nur für etwa 3 Monate lang zufriedener macht. Danach fallen wir automatisch wieder auf unser vorheriges Zufriedenheitslevel zurück. Achte lieber darauf, dass du dich konstant weiterentwickelst und echte Freude an deiner Arbeit hast.', '2	3	2	0	0	Ich muss Karriere machen	https://www.amazon.de/Die-Prinzipien-Erfolgs-Ray-Dalio/dp/3959721234/ref=sxbs_sxwds-stvp?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&cv_ct_cx=tony+robbins&keywords=tony+robbins&pd_rd_i=3959721234&pd_rd_r=09130408-7fe5-4aef-b7fc-4f4b89263733&pd_rd_w=8PW8Z&pd_rd_wg=18VwU&pf_rd_p=6d84c7ba-ae72-4e53-b9a4-5df18ccb370e&pf_rd_r=W82NBRRB0MF2MK289YQZ&psc=1&qid=1582549549&s=books	https://images-na.ssl-images-amazon.com/images/I/41HlLEiouCL._SX337_BO1,204,203,200_.jpg	Seine Firma Bridgewater Associates ist der größte Hedgefonds der Welt, er selbst gehört zu den Top 50 der reichsten Menschen auf dem Planeten: Ray Dalio. Seit 40 Jahren führt er sein Unternehmen so erfolgreich, dass ihn Generationen von Nachwuchsbankern wie einen Halbgott verehren. Mit »Die Prinzipien des Erfolgs« erlaubt er erstmals einen Blick in seine sonst so hermetisch abgeriegelte Welt. Die einzigartigen Prinzipien, mithilfe derer jeder den Weg des Erfolgs einschlagen kann, und die mitunter harten Lektionen, die ihn sein einzigartiges System errichten ließen, hat Ray Dalio auf eine bisher noch nie dagewesene, unkonventionelle Weise zusammengetragen.
        // ['Ich habe Angst zu scheitern', 'Was bedeutet scheitern für dich? Mache dir das im ersten Schritt klar. Grundsätzlich empfiehlt es sich, ein positives Mindset zum Thema scheitern zu entwickeln. Betrachte es mal so: Jedes Mal wenn du Fehler machst, lernst du etwas dazu und kannst es zukünftig besser machen. Wir Deutschen sind extrem sicherheitsbewusst und daher nicht besonders fehlerfreundlich. In den USA sieht das z.B. anders aus. Während du in Deutschland für Fehltritte gern kritisiert wirst, erzählen erfolgreiche Menschen in den USA voller Stolz von ihren größten Misserfolgen. Statistiken zeigen übrigens, dass die erfolgreichsten Menschen mindestens ein- bis zweimal gescheitert sind, bevor sie den Dreh raus hatten. Scheitern gehört dazu und definiert dich nicht als Person, sondern bezieht sich nur auf eine bestimmte Situation. Außerdem nimmt es dir den Druck, wenn du die Entscheidung triffst, Fehler machen zu dürfen. Nimm es mit spielerischer Gelassenheit.', '1	3	2	1	0	Ich kann das nicht	https://www.amazon.de/Kunst-spielerischen-Scheiterns-Selbstvertrauen-Clown-Methode/dp/3424631167/ref=sr_1_8?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=scheitern&qid=1582549890&s=books&sr=1-8	https://images-na.ssl-images-amazon.com/images/I/41gXt7yLDjL._SX310_BO1,204,203,200_.jpg	Freude ist pure Lebensenergie, sie schenkt uns Kraft und Selbstvertrauen. Doch wie können wir sie in kritischen Situationen bewahren, wenn die Angst vor Misserfolg uns lähmt? Darüber weiß Michael Stuhlmiller mehr als jeder andere, denn er ist Clown. Erstmals stellt er seine authentische und tausendfach erprobte »Clown-Methode« vor, die uns lehrt, selbst im Scheitern noch zu gewinnen: indem wir unsere Welt durch Spiel bewegen statt durch Druck. Dieses Buch bietet einen umfassenden psychologischen Werkzeugkasten, um aus Angst, Schüchternheit oder negativem Denken in die Freude zu finden.
        // ['Ich habe Angst meinen Job zu verlieren', 'Besteht denn eine begründete Sorge, dass du deinen Job verlieren könntest? Falls ja, schaue dir die Gründe an und überlege, welche du davon beeinflussen kannst und welche nicht. Wenn es z.B. an deiner Leistung liegt, könntest du daran arbeiten oder dir Unterstützung von deinem Chef oder Kollegen holen. Vielleicht geht es deinem Unternehmen aber auch schlecht und es werden Stellen gestrichen. Wenn Umstände für deine Angst verantwortlich sind, die du nicht beeinflussen kannst, gewinnst du die Kontrolle zurück, indem du aktiv wirst und z.B. anfängst, dich auf andere Stellen zu bewerben. Wenn du grundsätzlich ein ängstlicher Typ bist und ein komischer Blick deines Chefs ausreicht um dich zu verunsichern, solltest du eher nach Methoden suchen, mit denen du dein Selbstvertrauen stärken kannst.', '4	3	0	0	0	Ich bin nicht gut genug	https://www.amazon.de/Selbstbewusstsein-st%C3%A4rken-Glaubenss%C3%A4tze-Selbstzweifel-K%C3%B6rpersprache/dp/1099458978/ref=sr_1_4?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=selbstvertrauen+st%C3%A4rken&qid=1582550554&s=books&sr=1-4	https://images-na.ssl-images-amazon.com/images/I/51JWVg4rvfL._SX331_BO1,204,203,200_.jpg	Glaubenssätze erkennen, Selbstzweifel überwinden und durch Rhetorik und Körpersprache ihr Wohlbefinden stärken. Was dir diese Buch bringt: - Du erhältst einfache Übungen zur direkten Umsetzung an die Hand - Du wirst schon bald das Leben führen können, von dem du schon immer geträumt hast - Du bekommst alle wissenswerten Informationen rund um das Thema auf einen Blick - Du entdeckst Möglichkeiten dein Leben Schritt für Schritt in eine positive Richtung zu lenken
        // ['Mein Beruf erfüllt mich nicht', 'Erfüllung im Beruf ist einer der wichtigsten Glücksfaktoren. Eine Langzeitbefragung von Menschen, die nicht mehr lange zu leben hatten, hat ergeben, dass Sterbende u.a. am meisten bereuen, ihrer Berufung nicht gefolgt zu sein. Viele haben aus Angst sogar gar nicht erst danach gesucht, um im Alter dann schmerzlich festzustellen, dass es nun zu spät war. Frage dich ehrlich, welche Tätigkeit dich glücklich machen würde. Erinnere dich z.B. daran, was du als Kind werden wolltest und frage dich dann, welches Bedürfnis dahinter steht. Wolltest du z.B. Feuerwehrmann oder Ärztin werden, frge dich: Warum? Dahinter könnte das Verlangen stehen, dass du gern Menschen hilfst. Keine Sorge, du musst jetzt kein Medizinstudium beginnen. Obwohl du das natürlich tun kannst - es ist nie zu spät :-) Du kannst dich aber auch fragen, wie du deinen Wunsch, Menschen zu helfen, auf andere Weise erfüllen kannst. Wenn es bei dir ein anderes Bedürfnis ist, funktioniert das Prinzip genauso.', '9	3	2	1	0	Ich weiß nicht was ich will	https://www.amazon.de/Wishcraft-Lebenstr%C3%A4ume-Berufsziele-entdecken-verwirklichen/dp/3980920402/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2YJS42B9YVUR&keywords=barbara+sher&qid=1582546236&s=books&sprefix=barba%2Cstripbooks%2C164&sr=1-3	https://images-na.ssl-images-amazon.com/images/I/41brBuN%2BmPL._SX352_BO1,204,203,200_.jpg	Barbara Sher hilft, vage Wünsche und Ideen in greifbare Resultate zu verwandeln. Sie hilft ihren Lesern zu erkennen, was sie wirklich wollen, und zeigt, wie sie das, was sie wollen, schrittweise in ihr Leben holen können. "Wishcraft" ist ein Klassiker der Ratgeberliteratur, und überall da, wo es um Lebensplanung und Berufsfindung geht, ist es das Buch, zu dem man greift.
        // ['Ich würde mich gern selbständig machen', 'Immer mehr Arbeitnehmer wagen den Schritt in die Selbständigkeit, um unabhängiger zu sein und sich selbstzuverwirklichen. Der Begriff Beruf kommt von Berufung und in der Selbständigkeit haben wir die Freiheit, diese uneingeschränkt auszuleben. Nur wie gehst du das Thema konkret an? Der erste Schritt ist herauszufinden, womit du dich selbstverwirklichen willst. Wofür begeisterst du dich? Nur eine gute Geschäftsidee reicht nicht aus. Wenn du keine Leidenschaft für das Thema hast, wirst du vermutlich wie viele andere bei einem der ersten Hindernisse wieder aufhören und in dein altes Leben zurückkehren. Hast du diese Erkenntnis gewonnen, dir die notwendigen betriebswirtschaftlichen Kenntnisse anzueignen. Hast du schon? Umso besser. Wenn du die Entscheidung getroffen hast, mache dich darauf gefasst, dass du mit Hindernissen konfrontiert wirst. Der größte potenzielle Verhinderer bist jedoch du selbst. Wenn du z.B. zu perfektionistisch bist könnte das dazu führen, dass du nicht ins Handeln kommst. Oder du machst dir Sorgen, was andere von dir halten, was dich ebenfalls lähmt. Die Lösung besteht darin, die eigenen Blockaden zu verstehen und in positive Energie umzuwandeln.', '8	3	1	0	0	Mir fehlt der Mut	https://www.amazon.de/Selbst%C3%A4ndig-machen-Unternehmen-erfolgreichen-Existenzgr%C3%BCndung/dp/3965832794/ref=sr_1_1_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=der+weg+in+die+selbst%C3%A4ndigkeit&qid=1582551571&s=books&sr=1-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyUVpEVjVUR0g1UENEJmVuY3J5cHRlZElkPUEwMjg1MzI0MjBROFUxSUpZWDU4MSZlbmNyeXB0ZWRBZElkPUEwMzM0ODY5OTM2Szc5MTFJSzIwJndpZGdldE5hbWU9c3BfYXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==	https://images-na.ssl-images-amazon.com/images/I/51jWHIqFRFL._SX310_BO1,204,203,200_.jpg	Längst ist der Lebensweg für viele Menschen nicht mehr so vorherseh- und planbar, wie es noch vor wenigen Jahrzehnten selbstverständlich war! Dennoch ist der allgemeine Irrglaube, ein Angestelltenverhältnis wäre besonders sicher, immer noch sehr stark verbreitet, wodurch viele Menschen vor alternativen Wegen zurückschrecken. Unternehmertum und Selbständigkeit müssen aber nicht zwangsläufig mit großen Risiken und Gefahren verbunden sein. Wenn Sie ein paar grundlegende Regeln beachten, dann können Sie Ihr Risiko bereits erheblich minimieren. Lernen Sie deshalb von Jenen, die es bereits erfolgreich geschafft haben sich selbstständig zu machen.




        // $names = ['beruf_und_karriere', 'familie' ,'freundschaften', 'koerper_und_gesundheit', 'partnerschaft', 'sexualitaet', 'spiritualitaet',];
        // $areas = AreaOfLife::all();

        // $area = AreaOfLife::where('name', 'beruf_und_karriere')->first();
        // Symptom::create([
        //     'name' =>
        //     'instant_help' =>
        //     'res_prio' =>
        //     'fear' =>
        //     'anger' =>
        //     'sadness' =>
        //     'belief' =>
        //     'recom_book_url' =>
        //     'recom_book_imag' =>
        //     'recom_book_description' =>
        //     'recom_program' =>
        // ])

   
    }
}
